### ISSUE TITLE
java.lang.IllegalArgumentException When header.yaml file is given as input 

### ISSUE THREAD

**Issue by ganeshnikam18** [Endava/cats#110]
**Describe the bug**
If we give header.yaml file as a input on the cats command line then we get below exception:

> vm:~/cats$ java -jar ./target/cats-runner.jar --fuzzers=StringFieldsRightBoundaryFuzzer --server=http://api-server.com  --contract=./swagger.yml --headers=./header.yml

[******][*******] ▶ Starting cats-11.0.1-SNAPSHOT, build time 2024-02-28T18:40:31Z UTC, platform Linux-6.5.0-21-generic-amd64
[******][*******] ⚙ Headers file: /cats/header.yml
[******][*******] ‼ Something went wrong while running CATS: java.lang.IllegalArgumentException: Cannot deserialize value of type `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]

This exception will come for any FileArguments like: --header, --refData --urlParam

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Run cats command for any specification with --headers <headers.yaml> file. Content of headers.yaml file could be as below:

> all:
    - X-API-Key:abc123
2. The program will crash with Exception  

**Expected behaviour**
The headers.yaml file should be read properly and those headers should be sent in the request.

**Comment by en-milie** [comment]
Hi @ganeshnikam18. Headers file syntax implies that headers are sub-elements of paths and `all`, not array values like in your example. This is why it crashes. It's probably a good idea to change a bit the message to suggest that it's an issue with the syntax.

**Comment by ganeshnikam18** [comment]
@en-milie Ok. Got it. The content of the header.yaml file should be as below:

> all:
      X-API-Key : abc123

It will then be converted to Object, Instead of ArrayList.

Sorry for the incorrect bug

**Comment by en-milie** [comment]
It should be as follows:

```yaml
all:
  X-API-Key: abc123
```

Notice the indentation of the `X-API-Key`. It needs 2 spaces in order to be a sub-element of `all`.

**Comment by ganeshnikam18** [comment]
Yes. Thanks for the clarification

**Comment by en-milie** [comment]
Closing this.
