### ISSUE TITLE
The project structure seems a bit confusing

### ISSUE THREAD

**Issue by pakillodecm** [Endava/cats#113]
We have found it difficult to understand the way the project is structured, as components are not separated clearly. We have not been able to differentiate the functionalities of the program itself. 
We suggest adding information to the README so that it is shown the functionality of each subfolder. 
An alternative could be to modify the folders in order to establish a clear difference between them.

**Comment by en-milie** [comment]
Hi @pakillodecm. Can you please be more specific about the areas where you found it confusing? A couple of example will help.

**Comment by en-milie** [comment]
Closing this as no response received.
