### ISSUE TITLE
README translation

### ISSUE THREAD

**Issue by Alvarogl04** [Endava/cats#115]
Hello, I am doing group work with other colleagues at the university and we have been tasked with analyzing CATS. One of the requests they make of us is that we contribute something to this project. Although we consider CATS to be perfectly documented, it might be nice to have the README in Spanish (we are Spanish). We know that Google translates it automatically, but it makes some literal translations and others that don't make sense, so we have made our own translation (without changing anything original). We hope this contribution is useful to you.
[README - Spanish.md](https://github.com/Endava/cats/files/14549997/README.-.Spanish.md)

**Comment by en-milie** [comment]
Hi @Alvarogl04. Thank you for this. I'll add the Spanish readme file in the repo.
