### ISSUE TITLE
Question: path parameters?

### ISSUE THREAD

**Issue by jamesfulford** [Endava/cats#12]
I love this project, by the way. Heard about you from TLDR newsletter, giving it a try on some of my APIs. (We have some internal tools, and yours is waaay easier to get to work with authentication, props to you :) )

I'm building APIs with Spring, so my springdoc-generated OAS specs can often have path parameters expressed like `/articles/{id}`, which I'm not sure how to pass in a valid ID for. Especially if these tests call my DELETE method too early, I might get lots of 404s giving false failures on later tests. Any advice?

**Comment by en-milie** [comment]
Thanks 😄. It's great hearing feedback (and maybe future improvements).

You can supply path parameters in 2 ways:
- via `--urlParams="key:value;key1=value1"`
- via the `--refData` file by saying something like:

```yaml 
/articles/{id}:
  id: 123
```

`DELETE` is a bit tricky to handle. Up until now I've used the following approach:
- have CATS first running for non-DELETE methods using `--httpMethods="POST,PUT,GET,PATCH"`
- have another run for `DELETE` where you actually baselines the `errors` you get; it's not ideal, I know

I'm currently working on a feature where I stack all the IDs I get from `POST` requests and play them back one by one during `DELETE`.  It's still in progress as it relies on conventions and still trying to figure out the most user friendly way to correlate them.

**Comment by jamesfulford** [comment]
Makes sense, I'll give that a shot. Thanks
