### ISSUE TITLE
How to fuzz only methods that are implemented?

### ISSUE THREAD

**Issue by krishna-aw** [Endava/cats#124]
How do I configure cats so that it calls the URLs with only the REST methods that are implemented? For example, I have a URL `/api/v1/organizations/{orgID}/users` where I implemented only the POST method for this. How do I restrict CATS to only fuzz with POST method and not other methods like GET, PUT, etc.? How do I customize the methods for each URL separately?

**Comment by en-milie** [comment]
Hi @krishna-aw. CATS is very customizable. You can see the full arguments by doing a `cats --help`. In your case, you can restrict CATS to run only for the given path and only for `POST` using:

`cats -c api.yml -s http://yourservice --path "/api/v1/organizations/{orgID}/users" --httpMethod POST`
