### ISSUE TITLE
Out of bounds for length 0

### ISSUE THREAD

**Issue by ctwinovalon** [Endava/cats#125]
Ran --server xyz --contract file.json

Ran for a while on various endpoints and died on one of them with:

```
java.lang.StringIndexOutOfBoundsException: Range [-1, 0) out of bounds for length 0
...
com.endava.cats.generator.simple.StringGenerator.generateExactLength(StringGenerator.java:127)
```

**Comment by ctwinovalon** [comment]
Looks like this section: https://github.com/Endava/cats/blob/44fb35199dcdc17d12f23059ae3765687bdf841c/src/main/java/com/endava/cats/generator/simple/StringGenerator.java#L125-L132

The test ` if (initialValue.length() != length) {` should be ` if (initialValue > 0 && initialValue.length() != length) {`

**Comment by en-milie** [comment]
Hi @ctwinovalon. Can you please attach an  OpenApi spec i can use to reproduce the issue?

**Comment by ctwinovalon** [comment]
[api-docs3.json](https://github.com/Endava/cats/files/15485625/api-docs3.json)

**Comment by en-milie** [comment]
Thank you for providing the specs. This is now fixed in: https://github.com/Endava/cats/commit/1f936a9b8a80232a9bcb9a56f5e2c4b777fb38c7

**Comment by en-milie** [comment]
It should be fixed in: https://github.com/Endava/cats/releases/tag/cats-11.7.0
