### ISSUE TITLE
Incomplete group expression

### ISSUE THREAD

**Issue by ctwinovalon** [Endava/cats#128]
Testing the fix for #125 and the error now shows "[MLEVISF] Something went wrong while running CATS: java.lang.IllegalArgumentException: Incomplete group expression at position=2"

Presumably the previous example api json should work for this.

**Comment by en-milie** [comment]
I’ve tested with that json and it’s working fine. Might be another regex that fails to generate a proper value.

**Comment by en-milie** [comment]
@ctwinovalon can you please run cats with `--verbosity DETAILED --debug" and paste here the regex that fails?

**Comment by ctwinovalon** [comment]
Here you go!
```
 [*******][MLEVISF] Γù» Field initialLoginUrl has an associated schema
  [*******][MLEVISF] Γù» Generate for pattern ^(?i)(http:\/\/|https:\/\/)([a-z0-9./\-_.~+=:;%&?]+)$ min 11
  5 max 115
  [*******][MLEVISF] Γù» RGX generator failed, returning empty.: com.github.curiousoddman.rgxgen.parsing.d
  flt.RgxGenParseException: Unexpected symbol in pattern:
  '^(?i)(ht'
      ^
```

**Comment by en-milie** [comment]
It should be fixed in: https://github.com/Endava/cats/releases/tag/cats-11.7.0
