### ISSUE TITLE
Use all 3 type of authorization (Oauth , Api key and Basic Auth) on different paths present in swagger application

### ISSUE THREAD

**Issue by nayanmathur25** [Endava/cats#130]
I have a application where some request required ( Oauth and Basic Auth ) and some request required (API key with Basic Auth) and some only required Oauth or API Key. 
Do we have any feature where we can add all the 3 and based on the request it should use the Authorization.

API Authentication page https://endava.github.io/cats/docs/getting-started/authentication
 has very less details about the OAUTH

**Comment by en-milie** [comment]
CATS doesn't have integration with an oauth server, but you can use the answer from here: https://github.com/Endava/cats/issues/129 to provision tokens. If you need different authentication methods for each endpoint, you can use CATS by grouping common paths the share the same authentication method together using the `--path` argument filter. 

`cats -s SERVER -c CONTRACT --path "/path1,/path2,/path3" -H "Authorization: Bearer XXXX"` 

Similar for other paths that have different authentication needs.
