### ISSUE TITLE
CATS tool throughs exception for StringRightBoundary fuzzer when maxLength = 2147483647 (INT.MAX_VALUE)

### ISSUE THREAD

**Issue by ganeshnikam18** [Endava/cats#136]
**Describe the bug**
CATS tool exits with below exception:
**On IntelliJ IDE Terminal:**

> /pets .............................................................................................................................................................................................................. E 0, W 0, S 0 \[***4***][SFRB] ? Something unexpected happened: Java heap space

**On IntelliJ Debug Terminal:**
/pets .......................................................... E 0, W 0, S 0 \[***4***][SFRB] ? Something unexpected happened: Java heap space  

**To Reproduce**
Steps to reproduce the behaviour:
1. Petstore contract file to reproduce 
[petstore-right-boundary-fuzzer-memory-overflow-issue.json](https://github.com/user-attachments/files/16494958/petstore-right-boundary-fuzzer-memory-overflow-issue.json)

2. Use any server IP
3. User  --fuzzers=StringFieldsRightBoundary
5. CATS version: 11.7.1
6. Java version: 17.0.8.1+1 (build 17.0.8.1+1)

**Expected behaviour**
CATS tool should not crash

**Probable RCA:**
It seems that maxLength = 2147483647 (INT.MAX_VALUE) value is not handled properly in rightBoundaryFuzzer

**Comment by en-milie** [comment]
This should be fixed in 11.8.0. Can you please check if it's still reproducible? @ganeshnikam18

**Comment by en-milie** [comment]
@ganeshnikam18 Can I close this one?

**Comment by ganeshnikam18** [comment]
@en-milie You can close this. I have verified it in new version
