### ISSUE TITLE
 I have application which required bearer token  but getting unauthorized 401 for 28 request bcos cat is running the the 2nd request as **/api/logout** .

### ISSUE THREAD

**Issue by nayanmathur25** [Endava/cats#137]
Scenario: 
I have a swagger file which has around 30 request which includes login and logout functionality and i m using bearer token to login . When i m running the cats tool ,it runs the 2nd request as **/api/logout** and for rest of the application i m getting unauthorized 401.

Solution: 
 The cats running sequence should work in such a way that the logout or signout url should be handled at the last.

**Comment by en-milie** [comment]
@nayanmathur25 You can use `--skipPath "/api/logout"` to skip this specific path, and run `cats` only on that path after using `--path "/api/logout"`.

**Comment by en-milie** [comment]
I will close this for now. Please raise another ticket if the suggested approach doesn't work.
