### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by hidingturtle** [Endava/cats#138]
Hello,

I  wanted to ask if there is any HTTP/2 support since I was not able to find anything regarding it.

Best regards.

**Comment by en-milie** [comment]
Hi. The http library used by CATS supports http/2, so yes. Do you have any issues connecting to http/2 endpoints?

**Comment by hidingturtle** [comment]
Hi, I did not try it yet since I am looking if cats can serve my needs. Do I have to give a specific command for it or how can I enforce it to use HTTP/2?

**Comment by en-milie** [comment]
It will try by default using http/2 if server supports it. You don't need to provide anything specific.

**Comment by hidingturtle** [comment]
I understand, thank you! :)
