### ISSUE TITLE
Bypass Authentication doesnt work for Cookies

### ISSUE THREAD

**Issue by blackgrease** [Endava/cats#142]
**Describe the bug**
When the BypassAuthentication is run using the Cookies header, the scan generates 0 results and no requests are sent

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `cats --contract {docs} --server {server} --maxRequestsPerMinute 120 -f BypassAuthentication -H 'User-agent={useragent}' -H 'Cookie={cookie}'`
2. The command will execute but will not generate any tests. You can setup a HTTP Proxy for the scan to go through and no requests pass. 
3. To confirm, simply change the header to Authorization: The value does not matter as it will be removed anyway.

**Expected behaviour**
The Cats documentation for the fuzzer "Bypass Authentication" describes the fuzzer functionality as "this fuzzer removes any authentication headers from the requests. ". Cookies are a part of Authentication and cats should be able to detect either.

**Comment by en-milie** [comment]
Hi @blackgrease . Indeed, Cookies are not considered by the BypassAuthentication fuzzer. I'll add this feature.

**Comment by blackgrease** [comment]
Cheers @en-milie. Loving the tool so far.

**Comment by en-milie** [comment]
The fix is available in https://github.com/Endava/cats/releases/tag/cats-12.1.0

**Comment by blackgrease** [comment]
Yes I can confirm, it works now. Thanks
