### ISSUE TITLE
Cats not using provided API examples

### ISSUE THREAD

**Issue by blackgrease** [Endava/cats#143]
**Describe the bug**
When the flag --useExamples is explicitly set, cats still uses random data input. This is a problem as when running tests that require correct data in a POST/PUT/PATCH request, the request fails due to data validation not being passed. Which doesn't give proper insight into testing

**To Reproduce**
Steps to reproduce the behaviour:
1.cats --contract {docs} --server {server} --maxRequestsPerMinute 120 -A -f ExtraHeaders -H 'User-agent={useragent}' -H 'Authorization={other_jwt}' -g note,info -j -o BrokenFunctionality --proxyHost localhost --proxyPort 8090 --useExamples
2. The proxy is to see the result of the request. I have included a screenshot of the resulting request via the proxy. (Info identifying app has been removed). Any fuzzer that does not target fields has this issue.
3. 
![image](https://github.com/user-attachments/assets/19fa3234-d7a4-47ed-a4f3-3e889967a23d)

**Expected behaviour**
When --useExamples is set, the API data should be used instead of random inputs that will definitely cause the test to fail

**Comment by en-milie** [comment]
Hi @blackgrease. Indeed `--useExample` does not have first priority, but rather the internal generators. It is indeed a better idea to consider examples if available as first option and then generate.

**Comment by en-milie** [comment]
Fix will be available in 12.2.0. Documentation here: https://endava.github.io/cats/docs/getting-started/examples

**Comment by blackgrease** [comment]
Thank you, thatll be much appreciated

Sent from Proton Mail Android

-------- Original Message --------

**Comment by en-milie** [comment]
This is now available in: https://github.com/Endava/cats/releases/tag/cats-13.0.0

**Comment by blackgrease** [comment]
Thank you for such beautiful work
