### ISSUE TITLE
Typos in Docs

### ISSUE THREAD

**Issue by r4gus** [Endava/cats#145]
The documentation contains some minor typos including:
- `--verbosity=DEETAILED|SUMMARY` should be `--verbosity=DETAILED|SUMMARY` (https://endava.github.io/cats/docs/commands-and-arguments/arguments)
- `The script will replace any headers that have aut_script as value.` should be `The script will replace any headers that have auth_script as value.` (also included in the `cats --help` output)

Version: `CATS version 12.1.0`

**Comment by en-milie** [comment]
Thanks! Updated.
