### ISSUE TITLE
Client side rate limitting or throttling

### ISSUE THREAD

**Issue by deepkimchi** [Endava/cats#15]
Hi team. first of all thanks for the awesome library you built. The whole process was a breeze. 
Just wonder whether it support any type of Rate limit setup or have a plan for having something similar in the future.
I'm asking this because I came across multiple 503 from the API server while running it, the more Fuzzer CATS have, the more it act like a performance testing. :)

**Comment by en-milie** [comment]
I plan to do a commit with this tonight.

**Comment by en-milie** [comment]
This is now implemented under: https://github.com/Endava/cats/commit/de993c563c6bc2f215bb6394aa7f3a17156a4d8d You can use the `--maxRequestsPerMinute` argument to control the max requests per minute that CATS will send.

**Comment by en-milie** [comment]
This is now released in: https://github.com/Endava/cats/releases/tag/cats-6.0.5
