### ISSUE TITLE
Names for reports

### ISSUE THREAD

**Issue by comat0zz** [Endava/cats#23]
Is it possible to make it possible to give names to directories with reports? When several assemblies are launched in cd\ci, problems begin. As far as I see the option is to include a timestamp and parse the fuzzer's response to find out which timestamp. It would be very convenient if you could specify the option where the report will be saved and what name it will have. For exmaple:
cats ... -o /path/to/dir/**myreportname**/...
so you can operate on variables and paths in cd\ci

**Comment by en-milie** [comment]
@comat0zz This is now available in https://github.com/Endava/cats/commit/5a5d20f466c81016a5dc19ad33032a22fe839601
Just use `--output` or `-o` to set the output folder for the report.

**Comment by comat0zz** [comment]
:+1:
