### ISSUE TITLE
How disable colorization in non terminal system?

### ISSUE THREAD

**Issue by comat0zz** [Endava/cats#24]
Is it possible to disable colorization in the output? When it is displayed in the terminal, everything is fine, but when it is displayed on a page, for example, jenkins, then a lot of unnecessary things are visible, which makes it difficult to navigate. 

Example:
`[39m[38;5;188m[[39m[38;5;85m*[35;1mTest 376[m*[39m[38;5;188m][[39m[38;5;85m[35;1mVLVIFF[m*[39m[38;5;188m] [39m[38;5;231m[34m[1m● [1mnote[m       Path /signDocument has the following headers: null[39m[38;5;188m [39m[38;5;227m
[39m[38;5;188m[[39m[38;5;85m*[35;1mTest 376[m*[39m[38;5;188m][[39m[38;5;85m[35;1mVLVIFF[m*[39m[38;5;188m] [39m[38;5;231m[34m[1m● [1mnote[m       Headers that should be added to all paths: null[39m[38;5;188m [39m[38;5;227m
[39m[38;5;188m[[39m[38;5;85m*[35;1mTest 376[m*[39m[38;5;188m][[39m[38;5;85m[35;1mVLVIFF[m*[39m[38;5;188m] [39m[38;5;231m[34m[1m● [1mnote[m       Path reference data replacement: path /signDocument has the following reference data: {}[39m[38;5;188m [39m[38;5;227m
[39m[38;5;188m[[39m[38;5;85m*[35;1mTest 376[m*[39m[38;5;188m][[39m[38;5;85m[35;1mVLVIFF[m*[39m[38;5;188m] [39m[38;5;231m[34m[1m● [1mnote[m       Final list of request headers: [CatsRequest.Header(name=Accept, value=application/json), CatsRequest.Header(name=Content-Type, value=application/json)][39m[38;5;188m [39m[38;5;227m
[39m[38;5;188m[[39m[38;5;85m*[35;1mTest 376[m*[39m[38;5;188m][[39m[38;5;85m[35;1mVLVIFF[m*[39m[38;5;188m] [39m[38;5;231m[34m[1m● [1mnote[m       Final payload: `

**Comment by en-milie** [comment]
Hi @comat0zz. This is available in https://github.com/Endava/cats/commit/a4f8e7799211fb276ffb8486b4922008d246a9fc
In order to disable ANSI formatting, you need to set the [NO_COLOR](https://no-color.org/) system variable (with any value). 

`export NO_COLOR=true`

CATS will output plaint text with no formatting.

**Comment by comat0zz** [comment]
:+1:
