### ISSUE TITLE
HTTP method not supported yet! 

### ISSUE THREAD

**Issue by comat0zz** [Endava/cats#25]
Hi! Works great in cats.jar, but cats-linux doesn't work as it should. 

./cats-linux --contract=swagger.json --server=https://api/docs 

Powered by Quarkus 2.6.2.Final
[**********][*******] ▶ start      Starting CATS, version 7.0.3, build-time 2022-01-18T18:54:52Z UTC 
[**********][*******] ● note       Processing configuration... 
[**********][*******] ℹ info       No security custom Fuzzer file. SecurityFuzzer will be skipped! 
[**********][*******] ℹ info       No custom Fuzzer file. CustomFuzzer will be skipped! 
[**********][*******] ℹ info       No reference data file was supplied! Payloads supplied by Fuzzers will remain unchanged! 
[**********][*******] ℹ info       No URL parameters supplied! 
[**********][*******] ℹ info       No headers file was supplied! No additional header will be added! 
[**********][*******] ☑ complete   Finished parsing the contract in 21 ms 
[**********][*******] ℹ info         
[**********][*******] ▶ start      Start fuzzing path /canUserSignDocument 
[**********][*******] ⚠ warning    Skipping path /canUserSignDocument. HTTP method not supported yet! 
[**********][*******] ℹ info         
[**********][*******] ▶ start      Start fuzzing path /signDocument 
[**********][*******] ⚠ warning    Skipping path /signDocument. HTTP method not supported yet! 
[**********][*******] ≫ skipping   Skip printing time execution statistics. You can use --printExecutionStatistics to enable this feature! 
[**********][*******] ☑ complete   CATS finished in 2 ms. Total (excluding skipped) requests 0. ✔ Passed 0, ⚠ warnings: 0, ‼ errors: 0, ❯ skipped: 0. You can open the report here: file:///..../cats_fuzz/cats-report/index.html 

swagger file https://pastebin.com/dRkjCFbZ

**Comment by en-milie** [comment]
Hi @comat0zz. Seems to be same root cause as the other Swagger 2 spec issues. Should be (ideally) fixed in https://github.com/Endava/cats/releases/tag/cats-7.0.4

**Comment by comat0zz** [comment]
Thx!
