### ISSUE TITLE
Ignoring results for a specific HTTP Response code

### ISSUE THREAD

**Issue by comat0zz** [Endava/cats#27]
It is necessary to discard the 4xx codes. So that it doesn’t even get into the results and doesn’t create files on them.
There is an option in the settings to **ignoreResponseCodes**, but it does not do exactly what we would like - it also creates files and moves the results to the success.
Now results are additionally processed by an external script to get rid of unnecessary HTTP response codes. Is it possible to add similar functionality to the fuzzer?

**Comment by en-milie** [comment]
Hi @comat0zz. Makes sense. I'll think about introducing a generic way to ignore specific results.

**Comment by comat0zz** [comment]
@en-milie :+1: Looking forward to this feature

**Comment by en-milie** [comment]
I added a new argument for this: `--skipReportingForIgnoredCodes` or `-k`. This will be available in 7.0.6.
