### ISSUE TITLE
GET and DELETE with bodies

### ISSUE THREAD

**Issue by Jiehong** [Endava/cats#31]
Hi,

Until the Http Query method is not ready (https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html), some GET and DELETE services have to be specified with a body, because the size of the queryParameters is higher [than the limit encountered in the wild](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers).

So, would it be possible to still fuzz the body part for GET and DELETE, if their openapi spec says they need one?

**Comment by en-milie** [comment]
Currently this is not possible. I'll investigate what it means to do this. There are usually limitations coming from http libraries which make this assumption. So introducing this might require a more complex for of ok-http and maybe other dependencies.

**Comment by en-milie** [comment]
Apache Http Client is even more restrictive. I've use it before switching to okhttp and it does a lot of other validations for allowed characters in headers, paths, etc. That was not working well with the concept of fuzzing. The JDK http client has the same restrictions as okhttp.

**Comment by en-milie** [comment]
I'll close this as won't implement.
