### ISSUE TITLE
Field fuzzers for strings not applied for path/query params

### ISSUE THREAD

**Issue by rand-guy** [Endava/cats#34]
For GET requests with query/path params of type String, I ran fuzzing and test cases weren't generated to set empty string, null value for those. Is there a way to fuzz those path/query param fields?

**Comment by en-milie** [comment]
@rand-guy Adding empty or null for GET path params will result in 404 as the request doesn't even reach the right controller most of the times. But it might make sense to test query parameters for null and empty values. The current Fuzzers are explicitly disabled for GET and DELETE. But I'll add these 2 Fuzzers for query params.

**Comment by en-milie** [comment]
This is now available in https://github.com/Endava/cats/commit/adb231b3a2975739ae9afe359c9154ac449501fd
Will release it in 7.0.6 this week.

**Comment by en-milie** [comment]
This is now available in: https://github.com/Endava/cats/releases/tag/cats-7.0.6
