### ISSUE TITLE
Adding a GUI to CATS?

### ISSUE THREAD

**Issue by pgmarc** [Endava/cats#35]
Have you considered adding a GUI to CATS anytime soon?
It could make the program more intuitive and easy to use for new users as they will interact directly with the GUI marking checkboxes with the different arguments they want to use. Basically implementing all current business logic of CATS to a GUI.

**Comment by en-milie** [comment]
Hi @pgmarc. Yes, but it's not started yet. Maybe in the next 6 months.

**Comment by en-milie** [comment]
Will close this for now.
