### ISSUE TITLE
Have we thought about integrating CATS into maven plugins?

### ISSUE THREAD

**Issue by nereus-east** [Endava/cats#36]
for example.
If I add maven plugin CATS into pom.xml.

> 
    <build>
        <plugins>
            <plugin>
                <groupId>xxxxxxxx</groupId>
                <artifactId>cats</artifactId>
            </plugin>
        </plugins>
    </build>

when I run mvn test,
then CATS will automatically run test based on `openapi.yaml` and local environment.

**Comment by en-milie** [comment]
Hi @nereus-east. Thank you for raising this. This might be a future feature, but not currently on the roadmap.

**Comment by nereus-east** [comment]
Thank you for your quick feedback!

**Comment by en-milie** [comment]
I'll close this for now.
