### ISSUE TITLE
apiKey after paths

### ISSUE THREAD

**Issue by dglee0307** [Endava/cats#48]
Hello, I got a question while working on this project.
I'm performing REST API fuzzing with this project, and the apiKey value should be added after the paths, do you know how to solve this?

I'll show you an example.

I used this command on linux(kali-linux-2021.4-installer-amd64.iso / VirtualBox)
cats --contract=swagger.json --server=https://[Server IP:Port]/mc2/rest --paths=/logs --headers=headers.yml --refData=refData.yml

This is the result I want
[Full Request Path]
https://[Server IP:Port]/mc2/rest/logs?apiKey={apiKey} ...

but that command running, results in this.
[Full Request Path]
https://[Server IP:Port]/mc2/rest/logs?qsearch=my6cCmm&amp;logfilterid=h7vYiDGvbU4sdtS&amp;pageSize=-9223372036854775808&amp;description=e3RFzlUje4KNA&amp;sensorname=0dWQSwwXK3Ym&amp;auditlogTypes=node%2Cnode&amp;startdate=gansB1kZyUD&amp;radiuspolicy=vzItvvzItvvvz&amp;userid=ycTo3opZ&amp;ssid=Z3DDL&amp;mac=oOCVg&amp;extrainfo=dD0aAmFjdT2fj&amp;nasporttype=zxRbJeIKlWnL&amp;nasport=xNplD0X3&amp;logschema=auditlog&amp;ip=10.10.10.20&amp;sort=ihMdoII&amp;nasmac=slC1yFsn&amp;deptname=hLVhCXLHp&amp;periodType=custom&amp;enddate=sw0Ci14IWkE&amp;loglevel=v336r2pRsee&amp;logid=Ur0ILlieO&amp;page=1&amp;nasip=10.10.10.20&amp;username=oc7YxAy2Pz

**Comment by en-milie** [comment]
Hi @dglee0307. Is the apiKey query param part of the Swagger specs?

**Comment by dglee0307** [comment]
Thanks to reply @en-milie. The parameter does not have an apiKey and requires an apiKey value to use the REST API, but the apiKey should be added after that path, not in the header.

**Comment by en-milie** [comment]
Currently you can only append query parameters which are part of the contract. I'll consider adding new parameters in a future release. Target for the release this week.

**Comment by dglee0307** [comment]
okay I see. Thank you Have a Nice day~!

**Comment by en-milie** [comment]
I've added a `--queryParams` argument which is accepting a file similar to the `--headers` one where you can supply `key: value` for selected paths.

**Comment by dglee0307** [comment]
Thank you very much for the new version :)
I was execute cats, I have one question.
I received this report
-------------------------------------------------
"jsonBody": {
    "notAJson": "Unrecognized token 'np_period': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 11]"
  }
-------------------------------------------------
I saw currently supported class by the Limitations section in README.md, org.glassfish.jersey.message.internal.ReaderInterceptorExecutor class is not supported?
how can i solve this problem?
have a nice day!

**Comment by en-milie** [comment]
This means that your service is not behaving correctly i.e. CATS discovered a bug on how your service parses weird characters in the `np_period` field. Instead of failing gracefully with a proper validation error, it just crashes internally.

**Comment by dglee0307** [comment]
then, how can i see this test report error message?
In the example, I saw the error message (OPEN API petstore case)

**Comment by en-milie** [comment]
you should search in your application or server logs and see the stacktrace of the failure. CATS only reports what comes back from the service. (CATS reports are written in the `cats-report` folder. just open the index.html)

**Comment by dglee0307** [comment]
Thanks :)
