### ISSUE TITLE
X-Frame-Options vs Content-Security-Policy in CheckSecurityHeaders

### ISSUE THREAD

**Issue by NicolasCARPi** [Endava/cats#53]
Hello,

First, let me tell you that `cats` is a really great piece of software, congrats!

# Issue

The fuzzer CheckSecurityHeaders checks if X-Frame-Options is present in the response, but as can be seen on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options):

![2022-12-02-173413_789x112_scrot](https://user-images.githubusercontent.com/3043706/205340617-7901fa93-e538-4b4d-ac9f-60e9b18a081a.png)

My app doesn't have a X-Frame-Options header, but has a CSP with `frame-ancestors 'none'`.

I suggest that the fuzzer validates the test if this string is present in the CSP header.

Best,
~Nico

**Comment by en-milie** [comment]
Hi @NicolasCARPi. Thanks! I hope it will prove useful. 

Makes sense. I'll update the fuzzer to check for this header.

**Comment by en-milie** [comment]
Hi @NicolasCARPi. This is available in https://github.com/Endava/cats/releases/tag/cats-8.4.0.

**Comment by NicolasCARPi** [comment]
Thank you Madalin!
