### ISSUE TITLE
When multiple values are required for one parameter

### ISSUE THREAD

**Issue by dglee0307** [Endava/cats#54]
Hello, I have a question using CATS.

I am testing the REST API.
While testing the parameters, the 1:1 matching parameters go well in CATS.
1:N, i.e., when multiple values are required for one parameter, CATS does not seem to recognize it.
Do you know the solution to this problem?
Is it not recognized when multiple values are required for one parameter in CATS?

Thank you.

**Comment by en-milie** [comment]
Hi @dglee0307 . Can you please post an example of the expected behaviour?

**Comment by dglee0307** [comment]
For example, I understand that the key: value format is required for REST API testing.
When I tested it, the key:value in 1:1 format was successful.
ex. userId: admin
However, if the key:value is in the 1:N format, the test failed.
ex. body: value1, value2, value3

Do you happen to know why?
Am I not using CATS properly?

**Comment by en-milie** [comment]
I still miss the context :). Can you please just put a concrete example of an OpenAPI spec and how you actually run vs. what you expect to happen?

**Comment by en-milie** [comment]
Hi @dglee0307. Do you still need help on this one?

**Comment by dglee0307** [comment]
No, this problem is solved. Thank you. @en-milie
