### ISSUE TITLE
Feature Request: Support OpenAPI links for dependent requests

### ISSUE THREAD

**Issue by jasikpark** [Endava/cats#55]
https://swagger.io/docs/specification/links/ may be a start to automating creation of resources, though I guess that would require more management of what resource ids are valid..

**Comment by jasikpark** [comment]
Similar to Functional tests but written into the OpenAPI doc!

**Comment by DominickMad** [comment]
code

**Comment by en-milie** [comment]
Hi @jasikpark . No, it doesn't support this yet. You can achieve similar functionality, as you mentioned, using the `cats run ...` which accepts a YAML file with a simple DSL for writing and linking tests. 
Additionally, there are some fuzzers which have some intelligence, which will automatically identify the links between POST and GET/DELETE endpoints based on conventions.

**Comment by jasikpark** [comment]
do you have any recommendations for those fuzzers?

**Comment by en-milie** [comment]
You can follow this guide to corelate tests. CATS will fill in most of the details, while you need to supply the correlations between responses and next requests.
Additionally, there is a functionality that caches POST responses and will try to reuse Resource Identifiers on subsequent DELETE calls. 
And lastly, there is a `CheckDeletedResourcesNotAvailableFuzzer` that will check if successful DELETEs are not returned through GET.
I hope it helps.

**Comment by en-milie** [comment]
@jasikpark Updated the previous comment with the actual guide. Apologies for missing it the first time. 
Can I close this issue?

**Comment by jasikpark** [comment]
I kinda want to turn the issue into a Feature Request for links support, but sure 🤷‍♀️

**Comment by en-milie** [comment]
Sure. I'll leave it open then. And look into how to introduce support for links in the future.
