### ISSUE TITLE
Positive test with CAT

### ISSUE THREAD

**Issue by dglee0307** [Endava/cats#56]
I understand that CATS is a tool for negative testing.
Can I do a positive test using CATS?

**Comment by en-milie** [comment]
Yes. CATS has a `HappyFuzzer` and a `ExamplesFieldsFuzzer` which will send positive testing scenarios. The first one will construct a requests that is compliant with all the constraints set in the OpenAPI file. The `ExamplesFieldsFuzzer` will iterate through examples defined in the OpenAPI specs and send them to the service endpoint.
Additionally, you can follow the steps here: https://endava.github.io/cats/docs/fuzzers/special-fuzzers/functional-fuzzer to create functional flows across multiple service calls. CATS will take care of generation of the request. You just need to do the wiring and configure response fields to request fields in the next service call.

**Comment by en-milie** [comment]
Hi @dglee0307. Do you need additional details?

**Comment by dglee0307** [comment]
sorry for reply.
thank you @en-milie
