### ISSUE TITLE
Feature Request: Additional HTTP Methods

### ISSUE THREAD

**Issue by adrianavcon** [Endava/cats#58]
Has adding more HTTP methods been considered? This could be useful for further testing APIs that support other methods.

**Comment by en-milie** [comment]
Hi @adrianavcon.  Can you please add more details about which HTTP methods would be useful? Currently it supports: POST, PUT, PATCH, GET (and HEAD) and DELETE.

**Comment by adrianavcon** [comment]
Thank you for your response. I appreciate the current support for HTTP methods in the tool. Maybe methods like CONNECT and TRACE could be useful for testing APIs that implement them.

**Comment by en-milie** [comment]
CONNECT is not part of the OpenAPI specs and TRACE is mostly debugging. CATS tests also for TRACE not being available through the endpoints. 
I will close this.
