### ISSUE TITLE
Translating CATS

### ISSUE THREAD

**Issue by luciaPG** [Endava/cats#59]
Have you ever considered linking CATS' documentation to a freelance translating site? So that non-English speakers who want to contribute to the project can understand the documentation.

**Comment by en-milie** [comment]
Hi @luciaPG. There is no immediate plan to translate CATS to other languages.

**Comment by Papichulojubilao** [comment]
Me gustaría saber como configurar CATS

**Comment by en-milie** [comment]
@Papichulojubilao. The documentation is available here: https://endava.github.io/cats/
I will close this issue for now as translation is not scope for the planned future.
