### ISSUE TITLE
NamingsContractInfoFuzzer does not allow operations in path names because they are in singular form

### ISSUE THREAD

**Issue by sebipirpi** [Endava/cats#6]
Since not all actions are logically linked to CRUD operations, you should be allowed to have endpoints which end with an operation name rather than a resource, in case the action is isolated.
https://www.finextra.com/blogposting/16402/nouns-and-verbs-in-the-world-of-apis
https://plonerestapi.readthedocs.io/en/latest/conventions.html
 
e.g. 
/devices/{id}/alerts/{id}/resend

CATS does not accomodate this approach, since it checks if the path ends with a plural noun, even if the beginning includes one which identifies a resource, in the case above, "alerts"

**Comment by sebipirpi** [comment]
I think this should also be allowed when the second to last path element is not a resource identifier, for operations such as "calculations/add", "encryptions/encrypt_using_aes"

**Comment by en-milie** [comment]
The second example is not valid. This shouldn't be seen as a good practice. What you should do is a `POST` on `/encryptions` with `{algorithm: AES, payload: ....}`.
For the first example I will read a bit more around general recommendations.

**Comment by en-milie** [comment]
This is now fixed in [v5.2.9](https://github.com/Endava/cats/releases/tag/cats-5.2.9).
Thanks @sebipirpi for reporting this.

**Comment by sebipirpi** [comment]
No problem. Thank you @en-milie for addressing it so quickly!
