### ISSUE TITLE
Suggestion about format generation

### ISSUE THREAD

**Issue by Playeira** [Endava/cats#60]
We recommend using RegExr instead of RgxGen to solve one of the limitations of this project.

Have a nice day!!!!!

**Comment by en-milie** [comment]
Hi @Playeira. Can you please be more specific about which library you are referring to?

**Comment by Playeira** [comment]
Sorry, we didn't mean to substitute RgxGen for RegExr, what we meant was  using it when CATS needs help processing complex expressions
