### ISSUE TITLE
Some suggestions for the project

### ISSUE THREAD

**Issue by karyouben** [Endava/cats#62]
hi!, First of all I wanted to thank you for the incredible work and how well the project is documented and the quality it has.

I wanted to tell you as a suggestion some improvements in the project after analyzing the source code, I have noticed that there are very few comments and it is difficult to understand some parts for someone new like me, on the other hand in the documentation it would be good to add a view that allows visualizing all the operation of cats at a higher level of abstraction and finally in the context mode, wouldn't it be possible to generate the tests without the need for a file --RefData?

That was all my suggestions, thank you very much!

**Comment by en-milie** [comment]
Hi @karyouben. Thank you for the suggestions. We'll take them into consideration for future work. To answer some of the questions: 
- yes, it's possible to generate test without `--refData`; see this https://endava.github.io/cats/docs/getting-started/running-cats/#blackbox-mode.
- all operations and arguments are available here: https://endava.github.io/cats/docs/category/commands-and-arguments

**Comment by en-milie** [comment]
I'll close this now.
