### ISSUE TITLE
About adding headers in fuzzing command

### ISSUE THREAD

**Issue by lipeng28** [Endava/cats#64]
Hi There
I have a question about providing headers in fuzzing command:
./cats -c swagger.yaml -s https://open.larksuite-pre.com/open-apis/merge/v1 -H=<Tenant-Key:xxx>
what is the exact option for -H? I tried a few combinations, but they all failed. 
In addition, if I specify "Tenant-Key" in the header option, does this value still get mutated? 

Thanks
Peng

**Comment by en-milie** [comment]
hi @lipeng28. The syntax is:
`./cats -c swagger.yaml -s https://open.larksuite-pre.com/open-apis/merge/v1 -H Tenant-Key=XXX. The supplied headers won't get mutated.

**Comment by lipeng28** [comment]
Thanks, however, I still found some errors caused by the following: 
Send [abugidas chars] in headers. Current header [Tenant-Key] [REPLACE with జ్ఞ\u200cా]. 
Looks like the headers still got mutated. Right?

**Comment by en-milie** [comment]
If the header is present in the OpenAPI definition, even you supply it through the command line, it will be fuzzed. But seems a good idea to add an `--skipHeaders` argument, similar to the `--skipFields` one.

**Comment by lipeng28** [comment]
Thanks
