### ISSUE TITLE
The token setting doesn't work in CATS

### ISSUE THREAD

**Issue by Hannah516** [Endava/cats#68]
Hello, I want to do API test for our internal website. 
I set the token in the header file like:
all:
  Authorization: Token aaaaaaaaaaaaaaaaa
and run the cmd:java -jar cats.jar --contract=simple.yaml --blackbox --server=http://109.105.***.**:8080/v1 --headers=headers.yaml, 
But the report of CATS display the request header like:
[ { "key": "Accept", "value": "application/json" }, { "key": "Content-Type", "value": "application/json" } ].

Also I set the token in the cmd line like:
java -jar cats.jar --contract=simple.yaml --server=http://109.105.***.**:8080/v1 -H "Authorization=aaaaaaaaaaaaaaa".
The request header is still:
[ { "key": "Accept", "value": "application/json" }, { "key": "Content-Type", "value": "application/json" } ].

So my question is how can I set the request header of "Authorization: token aaaaaaaaa"?
Thank you very much.

**Comment by en-milie** [comment]
Hi @Hannah516. Can you please confirm if you are using the latest version of CATS 8.6.2?

**Comment by Hannah516** [comment]
> Hi @Hannah516. Can you please confirm if you are using the latest version of CATS 8.6.2? You can check it with: `java -jar cats.jar --version`

I used latest version instead of v8.6.0. It works now. Thanks a lot.
