### ISSUE TITLE
Feature Request: Add support for test report generation in the replay command

### ISSUE THREAD

**Issue by beam-me-up** [Endava/cats#71]
## Overview
Currently, the replay command in the project does not generate a test report for the test run. This issue serves as a feature request to add support for test report generation in the replay command.

## Proposal
It would be beneficial to have the ability to create a test report similar to the existing functionality in the `cats` command. To achieve this, I recommend incorporating the `--output=` argument from the `cats` command, which allows specifying the file or folder for the test report output.

## Benefits
By implementing this enhancement, users will have the option to generate comprehensive test reports directly from the replay command. This feature will improve test result visibility and facilitate easier analysis of the test run.

**Comment by en-milie** [comment]
The feature is available in: https://github.com/Endava/cats/releases/tag/cats-8.7.0
