### ISSUE TITLE
CATS 9.0.1 convert all components of the contract  to String

### ISSUE THREAD

**Issue by fviracacha-endava** [Endava/cats#75]
Good day,

With CATS version 9.01  we have noticed  that the values defined in the API contract for all components are being converted to STRING character, this behavior is creating a failure:

CATS ver 8.7.1 the card "number" and “cvv” are declared in the contract as a string, but the numerical values are not recognized by CATS:

![QA_CATS871_String](https://github.com/Endava/cats/assets/142629154/99b18051-d5a3-4511-881c-6c8a206cb04c)

CATS ver 9.0.1 all values are showed as string including the Boolean one:

![QA_CATS901_String](https://github.com/Endava/cats/assets/142629154/2afdd6a8-49b7-4a34-b64f-c8d23f528833)

Regards,
Fredy Viracachá

**Comment by fviracacha-endava** [comment]
Excuses, I forgot to add the CATS 9.0.1 response
![image](https://github.com/Endava/cats/assets/142629154/794e6246-f903-4d30-a729-b941baff58a7)

**Comment by vasil-nikolov** [comment]
Is there any progress with this one?

**Comment by en-milie** [comment]
Thank you for reporting this. Will pick it up this week.

**Comment by en-milie** [comment]
This should be fixed in https://github.com/Endava/cats/commit/123fa8f7d1a387b4554f69e7b8b76bc901262705 and will be available in next release.

**Comment by en-milie** [comment]
This is fixed now in: https://github.com/Endava/cats/releases/tag/cats-9.0.2
