### ISSUE TITLE
Request for Guidance: Writing a Functional Fuzzer for OpenAPI Specs with Missing Keys

### ISSUE THREAD

**Issue by beam-me-up** [Endava/cats#81]
I'm interested in learning how to write a functional fuzzer for OpenAPI specifications that lack keys. To illustrate, I have provided a sample OpenAPI spec below:

```yaml
/users:
    post:
      description: This API is used to get the list of users based on the input data.
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
```

In this example, the OpenAPI spec is missing keys that are typically present. I would greatly appreciate some guidance or best practices on how to approach fuzzing such specifications effectively.

**Comment by beam-me-up** [comment]
Sure @en-milie, here is the curl command sample for the above request. 

```curl
curl --location --request POST 'http://localhost:8080/users' \
--header 'Content-Type: application/json' \
--data-raw '"dGVzdERhdGE="'
```

This is a valid body. As a content-type as json, the body is expected to have a JSON object, array or literal.

**Comment by en-milie** [comment]
Hi @beam-me-up. I want to resume this issue. And want to check if my understanding is correct. You would like to be able to check if the a certain request body is missing fields that you would typically expect? And deduct this from the endpoint name and http method? Or specify the expected fields in the functional fuzzer file?
It will help if you can provide a full example, like: 
- a full OpenAPI sample spec
- what additional data you would expect to feed CATS with, either via the functional fuzzer file or arguments
- what would you expect the output of CATS to be

Thanks!

**Comment by en-milie** [comment]
Currently it's a 'no'.
