### ISSUE TITLE
SecurityFuzzer stringFile enhancement

### ISSUE THREAD

**Issue by olicau** [Endava/cats#84]
hello, first excellent tool :) I love it.
I am using in my security fuzzer a file called big-list-of-naughty-strings as stringFile.
https://raw.githubusercontent.com/minimaxir/big-list-of-naughty-strings/master/blns.txt
I am noticing that line starting with # (comments) and blank line are not being ignored.
Could be a nice enhancement to handle ignore those.

Thanks

**Comment by en-milie** [comment]
Thanks! Makes sense :) I'll add these in the next release.

**Comment by en-milie** [comment]
Feature available in latest release: https://github.com/Endava/cats/releases/tag/cats-10.1.0
