### ISSUE TITLE
Requests pass, but values are not substituted 

### ISSUE THREAD

**Issue by s1267** [Endava/cats#86]
I am trying to run fuzzing from a yml file with instructions trying to run Functional Fuzzer with the following configuration
![image](https://github.com/Endava/cats/assets/64472647/499e307a-3455-4b66-82da-a1a7a86ef356)
    
and Security Fuzzer 
![image](https://github.com/Endava/cats/assets/64472647/7d625ae5-0f9a-4604-bb65-93c3bf47762c)
      
     Requests pass, but values are not substituted
     `curl  -X POST \
      -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: cats/10.0.0" \
      -d '{}' \
      http://localhost:6500/mfm/v1/services/` - is the CURL of the request that SecurityFuzzer is sending.
      
      `curl  -X GET \
      -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: cats/10.0.0" \
      \
      http://localhost:6500/mfm/v1/services//` -  is the CURL of the request that FunctionalFuzzer is sending.

**Comment by en-milie** [comment]
Hi @s1267. Would it be possible to also attach (at least a section of) the openapi spec and exact command you are using to run CATS?

**Comment by s1267** [comment]
> Hi @s1267. Would it be possible to also attach (at least a section of) the openapi spec and exact command you are using to run CATS?
[openapi.json](https://github.com/Endava/cats/files/13373793/openapi.json)

**Comment by en-milie** [comment]
This should be fixed in: https://github.com/Endava/cats/releases/tag/cats-10.1.0
Also, you need to change the OpenAPI version from the file from `"openapi": "3.1.0"` to `"openapi": "3.0.0"`. CATS doesn't support `3,1` yet.

**Comment by s1267** [comment]
Thank you so much for the fix. Everything works fine
