### ISSUE TITLE
Configurable Error Code Expectations

### ISSUE THREAD

**Issue by binaryArrow** [Endava/cats#89]
**Issue**
While using CATS in my project, I've found it to be a valuable tool. However, a challenge has surfaced with the `AbugidasInStringFields` Fuzzer. This particular fuzzer anticipates an error code of `400`, whereas my API, built with `restEasy` therefore implementing `JAX-RS`, is designed to return a `404`.

For Example the fuzzer is applied to query parameters of type `string` with the format `date`. As per the JAX-RS specification: [Link to JAX-RS Specification](https://github.com/jakartaee/rest/blame/master/jaxrs-spec/src/main/asciidoc/chapters/resources/_resource_field.adoc#L72-L83), query parameters that don't conform to the specified type (in this case, `date`) are expected to yield an error code of `404`.

This discrepancy arises because certain Field Fuzzers, including `AbugidasInStringFields`, anticipate an error code of `400`, which contradicts the JAX-RS specification.

**Proposal**
Introduce configurability for expected error codes in Field Fuzzers.

**Comment by en-milie** [comment]
Hi @binaryArrow. Thank you for raising this. I'll do a bit of investigation and get back.

**Comment by en-milie** [comment]
Support for configurable response codes is available starting with this commit : https://github.com/Endava/cats/commit/0bb6d87eeb90228f1ec85c04046bf5e988407179. And also in the next release.

**Comment by binaryArrow** [comment]
nice!

**Comment by en-milie** [comment]
Details about usage here: https://endava.github.io/cats/docs/advanced-topics/fuzzers-config
