### ISSUE TITLE
FeatureRequest/Integration With REST-Assured

### ISSUE THREAD

**Issue by suryajit7** [Endava/cats#90]
Currently installing and running CATS requires manual steps which further require providing Ref Data file, necessary Headers, Auths and Params, etc. 
All this can be easily simplified and enhanced by integrating it with the REST-Assured where we can do all of the above and create a proper framework for API testing.
The final product will look like a maven-repo which can be added as a dependency in POM or Gradle file.

**Comment by en-milie** [comment]
CATS was built as a CLI tool. It's true that is also published as a maven library in maven central and can be added as a dependency to your project: https://github.com/Endava/cats?tab=readme-ov-file#experimental-maven-dependency-for-programmatic-use, however this is experimental and some fuzzers will not properly work as CATS relies on a fork of okhttp which is not published on Maven Central. Using CATS in source code will be possible by doing a CatsMain.run() and passing all arguments, which again is not (yet) optimized.

**Comment by en-milie** [comment]
I will close this for now as not in scope for the near future.
